	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace P04201702.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 1/4/2017 9:54:21 AM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// P04201702 Domain objects
	
	public partial class Documentation : Entity<Documentation>
	{
		public Documentation() { }
		public Documentation(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string TitlePageVN { get; set; }
        public string TitlePageEN { get; set; }
        public string MetaDescriptionVN { get; set; }
        public string MetaDescriptionEN { get; set; }
        public string TitleVN { get; set; }
        public string TitleEN { get; set; }
        public string ImageAvatarUrlVN { get; set; }
        public string ImageAvatarUrlEN { get; set; }
        public string DescriptionVN { get; set; }
        public string DescriptionEN { get; set; }
        public string ContentVN { get; set; }
        public string ContentEN { get; set; }
        public string RoutingVN { get; set; }
        public string RoutingEN { get; set; }
        public string Category { get; set; }
        public string PageComponent { get; set; }
        public int? DisplayOrder { get; set; }
        public int? Level { get; set; }
        public bool IsActive { get; set; }
        public int? ParentId { get; set; }
        public bool IsLeaf { get; set; }
    }
}
