	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace P04201702.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 1/4/2017 9:54:21 AM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// P04201702 Unit-of-Work

	public partial class P04201702UnitOfWork : UnitOfWork
	{
		public P04201702UnitOfWork() : base(new P04201702Db()) { }
	}
}
