//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class adgroup
    {
        public int adgroupID { get; set; }
        public string ADgroupname { get; set; }
        public string desc_ { get; set; }
        public Nullable<double> value_ { get; set; }
    }
}
