//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adminID { get; set; }
        public string adminname { get; set; }
        public string password { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
        public int functionNo { get; set; }
        public string page_redirect { get; set; }
        public string folder_main { get; set; }
    }
}
