//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyBusinessFields = new HashSet<CompanyBusinessField>();
            this.CompanyBusinessTypes = new HashSet<CompanyBusinessType>();
            this.Members = new HashSet<Member>();
        }
    
        public int Id { get; set; }
        public int IdProvince { get; set; }
        public int IdBusinessLicenseType { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string AbbreviationName { get; set; }
        public string BrandName { get; set; }
        public Nullable<System.DateTime> FoundationDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string TaxCode { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public Nullable<int> Status { get; set; }
        public string Address { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual BusinessLicenseType BusinessLicenseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBusinessField> CompanyBusinessFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyBusinessType> CompanyBusinessTypes { get; set; }
        public virtual Province Province { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
