//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class cus_ads
    {
        public int cusID { get; set; }
        public string Name_daidien { get; set; }
        public string address_ { get; set; }
        public string company_ { get; set; }
        public string tel { get; set; }
        public string email_ { get; set; }
        public Nullable<int> typeid { get; set; }
        public Nullable<int> group_userid { get; set; }
    }
}
