//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int documentID { get; set; }
        public string Name { get; set; }
        public string Contents { get; set; }
        public string moredescription { get; set; }
        public string filename { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
        public System.DateTime datecreate { get; set; }
    }
}
