//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public decimal newsID { get; set; }
        public string title_ { get; set; }
        public int groupID { get; set; }
        public int userinputID { get; set; }
        public string keyword_ { get; set; }
        public string content_ { get; set; }
        public string image_ { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
        public System.DateTime fromdate_ { get; set; }
        public System.DateTime todate_ { get; set; }
        public string location { get; set; }
        public string moderator { get; set; }
        public string agenda { get; set; }
        public string shortdesc { get; set; }
        public Nullable<int> numview { get; set; }
        public bool option_ { get; set; }
        public bool iscomment { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
        public Nullable<bool> isdoitac { get; set; }
        public Nullable<int> parentid { get; set; }
    }
}
