//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_user
    {
        public int groupid { get; set; }
        public string groupname { get; set; }
        public bool isdelete { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
