//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMemberTitle
    {
        public int Id { get; set; }
        public int IdMember { get; set; }
        public int IdMemberTitle { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual MemberTitle MemberTitle { get; set; }
    }
}
