//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MemberMemberTitles = new HashSet<MemberMemberTitle>();
        }
    
        public int Id { get; set; }
        public int IdCompany { get; set; }
        public int IdEducationLevel { get; set; }
        public int IdEthnic { get; set; }
        public int IdReligion { get; set; }
        public int IdProvince { get; set; }
        public Nullable<int> Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public string AvatarUrl { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DayLeave { get; set; }
        public string ReasonLeave { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual Ethnic Ethnic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberMemberTitle> MemberMemberTitles { get; set; }
        public virtual Province Province { get; set; }
        public virtual Religion Religion { get; set; }
    }
}
