//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cms_ybanewEntities : DbContext
    {
        public cms_ybanewEntities()
            : base("name=cms_ybanewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adgroup> adgroups { get; set; }
        public virtual DbSet<cus_ads> cus_ads { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<group_user> group_user { get; set; }
        public virtual DbSet<Information> Informations { get; set; }
        public virtual DbSet<MailHost> MailHosts { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<projectsen> projectsens { get; set; }
        public virtual DbSet<tbl_ads> tbl_ads { get; set; }
        public virtual DbSet<tbl_albums> tbl_albums { get; set; }
        public virtual DbSet<tbl_club> tbl_club { get; set; }
        public virtual DbSet<tbl_event_news> tbl_event_news { get; set; }
        public virtual DbSet<tbl_events_comment> tbl_events_comment { get; set; }
        public virtual DbSet<tbl_events_users> tbl_events_users { get; set; }
        public virtual DbSet<tbl_faqs> tbl_faqs { get; set; }
        public virtual DbSet<tbl_laws> tbl_laws { get; set; }
        public virtual DbSet<tbl_photosalbum> tbl_photosalbum { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<imageupload> imageuploads { get; set; }
        public virtual DbSet<MailDetail> MailDetails { get; set; }
        public virtual DbSet<MailManagement> MailManagements { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<tbl_club_news> tbl_club_news { get; set; }
        public virtual DbSet<tbl_club_user> tbl_club_user { get; set; }
        public virtual DbSet<tbl_comments> tbl_comments { get; set; }
        public virtual DbSet<tbl_industry> tbl_industry { get; set; }
        public virtual DbSet<TBL_LOAIBAO> TBL_LOAIBAO { get; set; }
        public virtual DbSet<TBL_MUCLUC> TBL_MUCLUC { get; set; }
        public virtual DbSet<TBL_SOBAO> TBL_SOBAO { get; set; }
    }
}
