//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public decimal newsID { get; set; }
        public int groupID { get; set; }
        public int userinputID { get; set; }
        public string title_ { get; set; }
        public string keyword_ { get; set; }
        public string content_ { get; set; }
        public System.DateTime date_action { get; set; }
        public string image_ { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
        public System.DateTime datelastupdate { get; set; }
        public string shortdesc { get; set; }
        public int numview { get; set; }
        public Nullable<bool> isbao { get; set; }
        public Nullable<int> parentID { get; set; }
        public Nullable<bool> ishome { get; set; }
        public int vote { get; set; }
        public int priority { get; set; }
        public string poem { get; set; }
        public string urlsite { get; set; }
        public Nullable<bool> iscomment { get; set; }
        public Nullable<System.DateTime> date_view { get; set; }
        public Nullable<bool> isregister { get; set; }
        public Nullable<System.DateTime> date_close { get; set; }
        public Nullable<decimal> newsid_connect { get; set; }
    }
}
