//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int proid { get; set; }
        public string proname { get; set; }
        public Nullable<int> progroupid { get; set; }
        public Nullable<int> provinceid { get; set; }
        public string clientid { get; set; }
        public Nullable<int> pro_year { get; set; }
        public Nullable<short> metiarial { get; set; }
        public Nullable<bool> offshore { get; set; }
        public Nullable<int> soid { get; set; }
        public Nullable<int> lengh { get; set; }
        public Nullable<int> Diameter { get; set; }
        public string details { get; set; }
        public string img_icon { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<int> userid { get; set; }
        public string proname_en { get; set; }
        public string details_en { get; set; }
    }
}
