//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_faqs
    {
        public int faqid { get; set; }
        public string faq_name { get; set; }
        public System.DateTime date_ { get; set; }
        public string content_ { get; set; }
        public System.DateTime date_anwser { get; set; }
        public string content_anwser { get; set; }
        public bool isactive { get; set; }
        public int priority { get; set; }
    }
}
