//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ads
    {
        public int adID { get; set; }
        public int groupID { get; set; }
        public int Ad_cusID { get; set; }
        public string Adname { get; set; }
        public string image_ { get; set; }
        public string ad_desc { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<double> price_ { get; set; }
        public string url_link { get; set; }
        public Nullable<decimal> clicknum { get; set; }
        public bool ad_active { get; set; }
        public bool ad_delete { get; set; }
        public bool ischarge { get; set; }
        public System.DateTime datelastupdate { get; set; }
        public string fileattach { get; set; }
        public Nullable<double> totalmonth { get; set; }
        public Nullable<decimal> totalclick { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> f_width { get; set; }
        public Nullable<int> f_height { get; set; }
    }
}
