//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MUCLUC
    {
        public int MUCLUC_ID { get; set; }
        public Nullable<int> LOAIBAO_ID { get; set; }
        public Nullable<int> SOBAO_ID { get; set; }
        public string MUCLUC_NAME { get; set; }
        public string MUCLUC_DESC { get; set; }
        public string MUCLUC_KEYWORD { get; set; }
        public string MUCLUC_CONTENT { get; set; }
        public Nullable<int> MUCLUC_SORT { get; set; }
        public Nullable<byte> MUCLUC_ONOFF { get; set; }
        public Nullable<System.DateTime> MUCLUC_DATECREATE { get; set; }
    }
}
