//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SOBAO
    {
        public int SOBAO_ID { get; set; }
        public Nullable<int> LOAIBAO_ID { get; set; }
        public string SOBAO_NAME { get; set; }
        public string SOBAO_DESC { get; set; }
        public string SOBAO_BACKGROUND { get; set; }
        public Nullable<byte> SOBAO_ONOFF { get; set; }
        public Nullable<System.DateTime> SOBAO_DATECREATE { get; set; }
    }
}
