//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_albums
    {
        public int albumid_ { get; set; }
        public string albumname { get; set; }
        public int creater { get; set; }
        public bool isdelete { get; set; }
        public bool isactive { get; set; }
        public System.DateTime date_ { get; set; }
        public int roleaccess { get; set; }
        public Nullable<int> priority { get; set; }
        public string pic_ { get; set; }
        public Nullable<short> type_ { get; set; }
        public string desc_ { get; set; }
    }
}
