//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_club
    {
        public int clubid { get; set; }
        public string type { get; set; }
        public bool ishome { get; set; }
        public string club_name { get; set; }
        public string club_desc { get; set; }
        public string club_help { get; set; }
        public int club_album { get; set; }
        public int prirority_ { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
        public Nullable<int> dis_ { get; set; }
        public string pic_ { get; set; }
    }
}
