//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_events_users
    {
        public decimal events_com { get; set; }
        public decimal newsid { get; set; }
        public int userid { get; set; }
        public short option_ { get; set; }
        public System.DateTime date_ { get; set; }
        public string fullname { get; set; }
        public string position { get; set; }
        public string companyname { get; set; }
        public string phone { get; set; }
        public string sex_ { get; set; }
        public string email_ { get; set; }
        public string info_ { get; set; }
    }
}
