//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_personel
    {
        public decimal userid { get; set; }
        public string fullname { get; set; }
        public bool sex { get; set; }
        public string cmnd { get; set; }
        public string issueby { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string nativeaddress { get; set; }
        public string curaddress { get; set; }
        public string homephone { get; set; }
        public string mobiphone { get; set; }
        public string emailpersonel { get; set; }
        public string ethnic { get; set; }
        public string religous { get; set; }
        public string imagephoto { get; set; }
        public Nullable<System.DateTime> dateupdate { get; set; }
        public bool isdelete { get; set; }
        public string userinfo { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> districid { get; set; }
        public Nullable<int> wardid { get; set; }
        public Nullable<int> qualyfication { get; set; }
        public string maxim_ { get; set; }
        public string biophy_ { get; set; }
    }
}
