//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_club_user
    {
        public int userid { get; set; }
        public int clubid { get; set; }
        public string chucvu { get; set; }
        public System.DateTime date_join { get; set; }
        public bool ismanager { get; set; }
        public bool isactive { get; set; }
        public bool isdelete { get; set; }
    }
}
