//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comments
    {
        public int newsid { get; set; }
        public int commentid { get; set; }
        public System.DateTime datepost { get; set; }
        public bool isshow { get; set; }
        public string name_ { get; set; }
        public string email_ { get; set; }
        public string title { get; set; }
        public string content_ { get; set; }
        public Nullable<bool> isregister { get; set; }
    }
}
