//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOAIBAO
    {
        public int LOAIBAO_ID { get; set; }
        public string LOAIBAO_NAME { get; set; }
        public string LOAIBAO_CONTENT { get; set; }
        public Nullable<int> LOAIBAO_SORT { get; set; }
        public Nullable<byte> LOAIBAO_ONOFF { get; set; }
        public Nullable<System.DateTime> LOAIBAO_DATECREATE { get; set; }
    }
}
