//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_industry
    {
        public int industryid { get; set; }
        public string industryname { get; set; }
        public string industrydesc { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<double> priority { get; set; }
    }
}
