	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace Solution10.Domain
{ 
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 6/16/2017 4:52:34 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// Solution10 Domain objects
	
	public partial class DemoA : Entity<DemoA>
	{
		public DemoA() { }
		public DemoA(bool defaults) : base(defaults) { }

        public Guid? Oid { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? DateCreated { get; set; }
        public Guid? DemoB { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }
    }
	
	public partial class DemoB : Entity<DemoB>
	{
		public DemoB() { }
		public DemoB(bool defaults) : base(defaults) { }

        public Guid? Oid { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal	? Price { get; set; }
        public int? OptimisticLockField { get; set; }
        public int? GCRecord { get; set; }
    }
	
	public partial class ModuleInfo : Entity<ModuleInfo>
	{
		public ModuleInfo() { }
		public ModuleInfo(bool defaults) : base(defaults) { }

        public int? ID { get; set; }
        public string Version { get; set; }
        public string Name { get; set; }
        public string AssemblyFileName { get; set; }
        public bool? IsMain { get; set; }
        public int? OptimisticLockField { get; set; }
    }
	
	public partial class XPObjectType : Entity<XPObjectType>
	{
		public XPObjectType() { }
		public XPObjectType(bool defaults) : base(defaults) { }

        public int? OID { get; set; }
        public string TypeName { get; set; }
        public string AssemblyName { get; set; }
    }
}
