	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace CMS.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by PRO Spark, C# Edition, Version 4.5
    // # Generated on 11/2/2016 3:06:10 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// CMS Domain objects
	
	
    public partial class Content : Entity<Content>
	{
		public Content() { }
        public Content(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? PageComponentId { get; set; }
        public string Description { get; set; }
        public string ContentData { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ChangedOn { get; set; }
        public int ChangedBy { get; set; }
        public bool IsActive { get; set; }
        public int Priority { get; set; }
    }
    public partial class ContentAttribute : Entity<ContentAttribute>
    {
        public ContentAttribute() { }
        public ContentAttribute(bool defaults) : base(defaults) { }
        public int? Id { get; set; }
        public int? ContentId {get; set;}
        public string Name { get; set; }
        public string AttributeValue { get; set; }
        public int Type { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ChangedOn { get; set; }
        public int ChangedBy { get; set; }
        public int Language { get; set; }

    }
    public partial class PageComponent : Entity<PageComponent>
	{
		public PageComponent() { }
        public PageComponent(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ContentType { get; set; }
        public bool IsActive { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public DateTime? ChangedOn { get; set; }
        public int ChangedBy { get; set; }
    }

    public partial class Article : Entity<Article>
    {
        public Article() { }
        public Article(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string TitleVN { get; set; }
        public string TitleEN { get; set; }
        public string ImageAvatarVN { get; set; }
        public string ImageAvatarEN { get; set; }
        public string DescriptionVN { get; set; }
        public string DescriptionEN { get; set; }
        public string ContentVN { get; set; }
        public string ContentEN { get; set; }
        public string KeywordVN { get; set; }
        public string KeywordEN { get; set; }
        public string MetaKeywordVN { get; set; }
        public string MetaKeywordEN { get; set; }
        public string MetaDescriptionVN { get; set; }
        public string MetaDescriptionEN { get; set; }
        public string MetaFbAdmin { get; set; }
        public string MetaSiteNameFb { get; set; }
        public string MetaPushFb { get; set; }
        public string UrlVN { get; set; }
        public string UrlEN { get; set; }
        public string Type { get; set; }
        public int IndexVN { get; set; }
        public string PageComponent { get; set; }
        public bool IsActive { get; set; }
    }
    public partial class Image : Entity<Image>
    {
        public Image() { }
        public Image(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string TitleVN { get; set; }
        public string TitleEN { get; set; }
        public string ImageUrlVN { get; set; }
        public string ImageUrlEN { get; set; }
        public string DescriptionVN { get; set; }
        public string DescriptionEN { get; set; }
        public string KeywordVN { get; set; }
        public string KeywordEN { get; set; }
        public string UrlVN { get; set; }
        public string UrlEN { get; set; }
        public string Type { get; set; }
        public int IndexVN { get; set; }
        public int IndexEN { get; set; }
        public string PageComponent { get; set; }
        public bool IsActive { get; set; }
    }
    public partial class Setting : Entity<Setting>
	{
		public Setting() { }
        public Setting(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string Name { get; set; }
        public string SettingValue { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
    }
	
	
    public partial class UserComment : Entity<UserComment>
	{
		public UserComment() { }
        public UserComment(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public DateTime? CommentedOn { get; set; }
        public string CommentedBy { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int? WhatId { get; set; }
        public int ContentType { get; set; }
        public string CommentData { get; set; }
    }
}
