	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;
using CMS.Domain.Repository;

namespace CMS.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by PRO Spark, C# Edition, Version 4.5
    // # Generated on 11/2/2016 3:06:10 PM
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// CMS Context. hosts all repositories

	public static class CMSContext
	{
	    static Db db = new CMSDb();
		
		// entity specific repositories

        public static Contents Contents { get { return new Contents(); } }
        
        public static PageComponents PageComponents { get { return new PageComponents(); } }
        public static Settings Settings { get { return new Settings(); } }
        public static UserComments UserComments { get { return new UserComments(); } }
        public static ContentAttributes ContentAttributes { get { return new ContentAttributes(); } }
        public static Images Images { get { return new Images(); } }
        public static Articles Articles { get { return new Articles(); } }

        // general purpose operations

        public static void Execute(string sql, params object[] parms) { db.Execute( sql, parms ); }
        public static IEnumerable<dynamic> Query(string sql, params object[] parms) { return db.Query( sql, parms ); }
        public static object Scalar(string sql, params object[] parms) { return db.Scalar( sql, parms ); }

        public static DataSet GetDataSet(string sql, params object[] parms) { return db.GetDataSet( sql, parms ); }
        public static DataTable GetDataTable(string sql, params object[] parms) { return db.GetDataTable( sql, parms ); }
        public static DataRow GetDataRow(string sql, params object[] parms) { return db.GetDataRow( sql, parms ); }
	}
}
