
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace NamolyNomenclature.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 09/02/2017 8:08:37 CH
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################

    // NamolyNomenclature Domain objects

    public partial class BusinessEntity : Entity<BusinessEntity>
    {
        public BusinessEntity() { }
        public BusinessEntity(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string TaxCode { get; set; }
        public decimal? Longtitude { get; set; }
        public decimal? Latitude { get; set; }
        public string MapMarkerURL { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public bool IsHotel { get; set; }
        public bool IsRestaurant { get; set; }
        public bool IsSpa { get; set; }
        public bool IsOTA { get; set; }
        public bool IsTA { get; set; }
        public byte Status { get; set; }
    }

    public partial class BusinessEntityProperty : Entity<BusinessEntityProperty>
    {
        public BusinessEntityProperty() { }
        public BusinessEntityProperty(bool defaults) : base(defaults) { }

        public int? Id { get; set; }
        public int? BusinessEntityId { get; set; }
        public int Category { get; set; }
        public int PropertyKey { get; set; }
        public string PropertyValue { get; set; }
        public string Language { get; set; }
    }
}
