	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace NamolyNomenclature.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 09/02/2017 8:08:37 CH
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// NamolyNomenclature Context. hosts all repositories

	public static class NamolyNomenclatureContext
	{
		static Db db = new NamolyNomenclatureDb();
		
		// entity specific repositories

        public static BusinessEntities BusinessEntities { get { return new BusinessEntities(); } }
        public static BusinessEntityProperties BusinessEntityProperties { get { return new BusinessEntityProperties(); } }

		// general purpose operations

		public static void Execute(string sql, params object[] parms) { db.Execute( sql, parms ); }
		public static IEnumerable<dynamic> Query(string sql, params object[] parms) { return db.Query( sql, parms ); }
		public static object Scalar(string sql, params object[] parms) { return db.Scalar( sql, parms ); }

		public static DataSet GetDataSet(string sql, params object[] parms) { return db.GetDataSet( sql, parms ); }
		public static DataTable GetDataTable(string sql, params object[] parms) { return db.GetDataTable( sql, parms ); }
		public static DataRow GetDataRow(string sql, params object[] parms) { return db.GetDataRow( sql, parms ); }

        public static Hotels Hotels { get { return new Hotels(); } }

    }
}
