	
using System;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections.Generic;

namespace NamolyNomenclature.Domain
{
    // ############################################################################
    // #
    // #        ---==>  T H I S  F I L E  W A S  G E N E R A T E D  <==---
    // #
    // # This file was generated by the CodeGen Prototype
    // # Generated on 09/02/2017 8:08:37 CH
    // #
    // # Edits to this file may cause incorrect behavior and will be lost
    // # if the code is regenerated.
    // #
    // ############################################################################
	
	// NamolyNomenclature Unit-of-Work

	public partial class NamolyNomenclatureUnitOfWork : UnitOfWork
	{
		public NamolyNomenclatureUnitOfWork() : base(new NamolyNomenclatureDb()) { }
	}
}
