//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityWithMysql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_History
    {
        public int Id { get; set; }
        public string NameSpace { get; set; }
        public string Data { get; set; }
    }
}
